services:
  bot:
    build: .
    container_name: ai_voice_bot
    restart: always
    env_file:
      - .env
    environment:
      - DOCKER_MODE=true ##чтобы нормально делать миграции и не менять локалхост на дб
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ai_voice_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
