version: '3.8'

services:
  bot:
    build: .
    container_name: ai_voice_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: bot_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
